
# Set the base image
FROM python:3.13-trixie

# File Author / Maintainer
LABEL image.author="frank@schlottmann-goedde.de"
ARG USERNAME=shiva
ARG USER_UID=1000
ARG USER_GID=$USER_UID
ARG USER_PW=shiva

RUN apt-get update && apt-get -y upgrade && apt-get install -y sudo \
    psmisc libmp3lame-dev libflac-dev libxml2-dev \
    libshout-dev libvorbis-dev libogg-dev libfaad-dev libpython3-dev libperl-dev \
    libtommath1 \
    && apt-get clean \
    && apt-get autoremove \
    && rm -rf /var/lib/apt/lists/*

RUN useradd --create-home --shell /bin/bash  $USERNAME  && \
    mkdir -p /home/$USERNAME/app && \
    chown $USERNAME:$USERNAME /home/$USERNAME/app && \
    echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME   &&\
    chmod 0440 /etc/sudoers.d/$USERNAME


WORKDIR /home/$USERNAME/app
USER $USERNAME
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
#USER $USERNAME
COPY ./*.py .
COPY --from=build --chown=shiva:shiva /ices0/build/src/ices .
RUN sudo chown $USERNAME:$USERNAME *.*
#CMD [ "sleep", "infinity" ]
CMD [ "python", "indexmedia.py" ]
