FROM python:3.13-trixie AS build
LABEL authors="frank"
RUN apt-get update
RUN apt-get update
RUN apt-get install -y git build-essential cmake libmp3lame-dev libflac-dev libxml2-dev libshout-dev libvorbis-dev libogg-dev libfaad-dev libpython3-dev libperl-dev
RUN git clone https://github.com/franksgg/ices0.git
WORKDIR /ices0
RUN mkdir "build"
#RUN cmake --help
RUN cmake -S . -B build -DCMAKE_BUILD_TYPE=Release \
      -DWITH_XML=ON -DWITH_PYTHON=ON -DWITH_PERL=ON -DWITH_LAME=ON \
      -DWITH_VORBIS=ON -DWITH_FAAD=ON -DWITH_FLAC=ON
RUN cmake --build build


# Set the base image
FROM python:3.13-trixie

# File Author / Maintainer
LABEL image.author="frank@schlottmann-goedde.de"

RUN apt-get update && apt-get -y upgrade && apt-get install -y sudo \
    psmisc libmp3lame-dev libflac-dev libxml2-dev \
    libshout-dev libvorbis-dev libogg-dev libfaad-dev libpython3-dev libperl-dev \
    libtommath1 \
    && apt-get clean \
    && apt-get autoremove \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /usr/src/app


COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN apt update
RUN apt install libtommath1
COPY ./*.py .
COPY --from=build /ices0/build/src/ices .
#CMD [ "sleep", "infinity" ]
CMD [ "python", "indexmedia.py" ]
