FROM python:3
WORKDIR /usr/src/app


COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN apt update
RUN apt install libtommath1
COPY ./*.py .

#CMD [ "sleep", "infinity" ]
CMD [ "python", "indexmedia.py" ]
